// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsogscaipffwkjszicfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzb2dzY2FpcGZmd2tqc3ppY2ZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUxODg3MTEsImV4cCI6MjA4MDc2NDcxMX0.QsK1D0ymysT6sBSIP428J6iF-JgZ7P5jRvsZkjTbtY4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});